collections:
- name: stolostron.core
  source: https://github.com/TheRealHaoLiu/stolostron.ansible-collection.core
  type: git
  version: fix-cluster-proxy-integration-for-acm-2.6
- name: kubernetes.core
- name: awx.awx
